name: "Aditya Agarwal's Blog"
favicon: null
layout_spectrum: 0.42028163466602564
typography_spectrum: 0.8163654108066112
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.47210864536464214
  lightness: 0.03761996002867818
  saturation: 0.4324442569632083
  rhythmicContrast: 0.8784651106689125
purpose: []
